### ISSUE TITLE
Signal Error when UnixSignalDeathPenalty is triggered

### ISSUE THREAD

**Issue by jackzzs** [eoranged/rq-dashboard#486]
**Describe the bug**
Error occurs and some page can not be loaded:
```
File ".../site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File ".../site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File ".../site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File ".../site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File ".../site-packages/rq_dashboard/web.py", line 111, in _wrapped
    result_dict = f(*args, **kwargs)
  File ".../site-packages/rq_dashboard/web.py", line 460, in list_queues
    queues = serialize_queues(instance_number, sorted(Queue.all()))
  File ".../site-packages/rq_dashboard/web.py", line 118, in serialize_queues
    return [
  File ".../site-packages/rq_dashboard/web.py", line 139, in <listcomp>
    started_job_registry_count=StartedJobRegistry(q.name).count,
  File ".../site-packages/rq/registry.py", line 89, in count
    self.cleanup()
  File ".../site-packages/rq/registry.py", line 238, in cleanup
    job.execute_failure_callback(
  File ".../site-packages/rq/job.py", line 1430, in execute_failure_callback
    with death_penalty_class(self.failure_callback_timeout, JobTimeoutException, job_id=self.id):
  File ".../site-packages/rq/timeouts.py", line 36, in __enter__
    self.setup_death_penalty()
  File ".../site-packages/rq/timeouts.py", line 69, in setup_death_penalty
    signal.signal(signal.SIGALRM, self.handle_death_penalty)
  File ".../signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```

**To Reproduce**
1. Send a rq task which is stopped due to timeout.
2. Do not try to load the status of this task.
3. Start rq-dashboard.
4. See error.

**Expected behavior**
No error.

**Screenshots**
![image](https://github.com/Parallels/rq-dashboard/assets/17276599/7d8f1f3d-7cba-499d-92a9-234e98aee6a5)

**Additional context**
 - Python Version [e.g. 3.7.3]

**Comment by rbange** [comment]
Getting a similar error:

```python
Exception on /dashboard/0/data/jobs/multi_optimization/started/8/1.json [GET]
Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/rq_dashboard/web.py", line 112, in _wrapped
    result_dict = f(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/rq_dashboard/web.py", line 491, in list_jobs
    total_items, jobs = get_queue_registry_jobs_count(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/rq_dashboard/web.py", line 270, in get_queue_registry_jobs_count
    total_items = current_queue.count
                  ^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/rq/registry.py", line 89, in count
    self.cleanup()
  File "/venv/lib/python3.12/site-packages/rq/registry.py", line 238, in cleanup
    job.execute_failure_callback(
  File "/venv/lib/python3.12/site-packages/rq/job.py", line 1430, in execute_failure_callback
    with death_penalty_class(self.failure_callback_timeout, JobTimeoutException, job_id=self.id):
  File "/venv/lib/python3.12/site-packages/rq/timeouts.py", line 36, in __enter__
    self.setup_death_penalty()
  File "/venv/lib/python3.12/site-packages/rq/timeouts.py", line 69, in setup_death_penalty
    signal.signal(signal.SIGALRM, self.handle_death_penalty)
  File "/usr/local/lib/python3.12/signal.py", line 58, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: signal only works in main thread of the main interpreter
```

The dashboard is run in a Kubernetes container.

**Comment by mccauleyp** [comment]
I see the same with the dashboard mounted on a FastAPI app. I believe this is happening because in `rq_dashboard/web.py`, there are lines like the following:
```
            failed_job_registry_count=FailedJobRegistry(q.name, connection=q.connection).count,
```
The `count` property actually has a side effect of triggering a cleanup behavior that can lead to callbacks being executed. See https://github.com/rq/rq/blob/master/rq/registry.py#L92

When that happens for a setup like mine where the dashboard is mounted to a FastAPI app, we hit the above error because it's not running in the main thread. 

I think it might be undesirable for the dashboard to trigger cleanup operations as a side effect of getting counts anyway, though, so maybe the best thing to do is to update those count lines to be:
```
            failed_job_registry_count=FailedJobRegistry(q.name, connection=q.connection).get_job_count(cleanup=False),
```
Then the `cleanup` behavior is left for the RQ internals. Alternatively, if it is desirable for the dashboard to trigger cleanups like this, the dashboard app could be updated to detect if it's running in the main thread and only set `cleanup=False` if not. But to me it was surprising that the dashboard would be trying to trigger failure callbacks, so I think `cleanup=False` should be the default behavior. 

Here is a diff to change all of the lines:
  ```diff
  diff --git a/rq_dashboard/web.py b/rq_dashboard/web.py
  index dd41bdc..2a8f0d0 100644
  --- a/rq_dashboard/web.py
  +++ b/rq_dashboard/web.py
  @@ -133,7 +133,7 @@ def serialize_queues(instance_number, queues):
                   order="asc",
                   page="1",
               ),
  -            failed_job_registry_count=FailedJobRegistry(q.name, connection=q.connection).count,
  +            failed_job_registry_count=FailedJobRegistry(q.name, connection=q.connection).get_job_count(cleanup=False),
               failed_url=url_for(
                   ".jobs_overview",
                   instance_number=instance_number,
  @@ -143,7 +143,7 @@ def serialize_queues(instance_number, queues):
                   order="asc",
                   page="1",
               ),
  -            started_job_registry_count=StartedJobRegistry(q.name, connection=q.connection).count,
  +            started_job_registry_count=StartedJobRegistry(q.name, connection=q.connection).get_job_count(cleanup=False),
               started_url=url_for(
                   ".jobs_overview",
                   instance_number=instance_number,
  @@ -153,7 +153,7 @@ def serialize_queues(instance_number, queues):
                   order="asc",
                   page="1",
               ),
  -            deferred_job_registry_count=DeferredJobRegistry(q.name, connection=q.connection).count,
  +            deferred_job_registry_count=DeferredJobRegistry(q.name, connection=q.connection).get_job_count(cleanup=False),
               deferred_url=url_for(
                   ".jobs_overview",
                   instance_number=instance_number,
  @@ -163,7 +163,7 @@ def serialize_queues(instance_number, queues):
                   order="asc",
                   page="1",
               ),
  -            finished_job_registry_count=FinishedJobRegistry(q.name, connection=q.connection).count,
  +            finished_job_registry_count=FinishedJobRegistry(q.name, connection=q.connection).get_job_count(cleanup=False),
               finished_url=url_for(
                   ".jobs_overview",
                   instance_number=instance_number,
  @@ -173,7 +173,7 @@ def serialize_queues(instance_number, queues):
                   order="asc",
                   page="1",
               ),
  -            canceled_job_registry_count=CanceledJobRegistry(q.name, connection=q.connection).count,
  +            canceled_job_registry_count=CanceledJobRegistry(q.name, connection=q.connection).get_job_count(cleanup=False),
               canceled_url=url_for(
                   ".jobs_overview",
                   instance_number=instance_number,
  @@ -183,7 +183,7 @@ def serialize_queues(instance_number, queues):
                   order="asc",
                   page="1",
               ),
  -            scheduled_job_registry_count=ScheduledJobRegistry(q.name, connection=q.connection).count,
  +            scheduled_job_registry_count=ScheduledJobRegistry(q.name, connection=q.connection).get_job_count(cleanup=False),
               scheduled_url=url_for(
                   ".jobs_overview",
                   instance_number=instance_number,
  ```
To workaround this for now, I'm patching the dashboard like so:
```
import os

import rq_dashboard
from flask import Flask
from rq.registry import BaseRegistry
from rq_dashboard.cli import add_basic_auth

# Patch rq_dashboard.web.serialize_queues to disable cleanup during registry counts.
# This prevents "signal only works in main thread" errors when rq-dashboard tries
# to display queue counts. See: https://github.com/Parallels/rq-dashboard/issues/486
_original_serialize_queues = rq_dashboard.web.serialize_queues
_original_get_job_count = BaseRegistry.get_job_count


def _patched_serialize_queues(instance_number, queues):  # type:ignore[no-untyped-def]
    BaseRegistry.get_job_count = lambda self, cleanup=True: _original_get_job_count(
        self, cleanup=False
    )
    try:
        return _original_serialize_queues(instance_number, queues)
    finally:
        BaseRegistry.get_job_count = _original_get_job_count


rq_dashboard.web.serialize_queues = _patched_serialize_queues


class DashboardConfig(object):
    RQ_DASHBOARD_REDIS_URL = f"redis://{os.getenv('RQ_HOST', 'localhost')}:6379"


dashboard_app = Flask(__name__)
dashboard_app.config.from_object(DashboardConfig)
rq_dashboard.web.setup_rq_connection(dashboard_app)
add_basic_auth(rq_dashboard.blueprint, username="", password=os.environ["API_KEY"])
dashboard_app.register_blueprint(rq_dashboard.blueprint, url_prefix="/dashboard")
```
Then in my FastAPI app, I have:
```
app.mount("/rq", WSGIMiddleware(dashboard_app))
```
